### cgcrepair Configuration Settings
---

cgcrepair:

### Toggle application level debug (does not toggle framework debugging)
  debug: false

### Where external (third-party) plugins are loaded from
# plugin_dir: /var/lib/cgcrepair/plugins/

### Where all plugin configurations are loaded from
# plugin_config_dir: /etc/cgcrepair/plugins.d/

### Where external templates are loaded from
# template_dir: /var/lib/cgcrepair/templates/

### The log handler label
  log_handler: colorlog

### The output handler label
  output_handler: jinja2

### Testing
  tests_timeout: 60
  margin: 5
  cores: "/cores"

### Bindings
  python2: "python2"
  lib: "/usr/local/lib/cgc"
  include: "/usr/local/include/cgc"

### Output
  plots: './plots'
  working_dir: '/tmp'

### Parsing
  cwe_level: 3


log.colorlog:

### Where the log file lives (no log file by default)
  file: '/home/epicosy/Apps/cgc-repair/cgc-repair.log'

### The level for which to log.  One of: info, warning, error, fatal, debug
  level: info

### Whether or not to log to console
  to_console: true

### Whether or not to rotate the log file when it reaches `max_bytes`
  rotate: true

### Max size in bytes that a log file can grow until it is rotated.
  max_bytes: 512000

### The maximun number of log files to maintain when rotating
  max_files: 4
