### cgcrepair Configuration Settings
---

cgcrepair:

### Toggle application level debug (does not toggle framework debugging)
  debug: true

### Where external (third-party) plugins are loaded from
# plugin_dir: /var/lib/cgcrepair/plugins/

### Where all plugin configurations are loaded from
# plugin_config_dir: /etc/cgcrepair/plugins.d/

### Where external templates are loaded from
# template_dir: /var/lib/cgcrepair/templates/

### The log handler label
  log_handler: colorlog

### The output handler label
  output_handler: jinja2

### Testing
  tests_timeout: 60
  margin: 5
  cores: "/cores"

### Bindings
  python2: "python2"
  lib32: "/usr/local/lib32/cgc"
  lib64: "/usr/local/lib64/cgc"
  include: "/usr/local/include/cgc"
  corpus: "/usr/local/src/cgc"
  tools: "/usr/local/share/pyshared/cgc"
  polls: "/usr/local/share/polls"
  povs: "/usr/local/share/povs"

### Output
  plots: './plots'
  root_dir: '/tmp'

### CWE Parsing
  cwe_level: 3
  metadata: "/etc/cgcrepair/metadata.yml"

### Database configs
  dialect: 'postgresql'
  username: 'cgcrepair'
  password: 'cgcrepair123'
  host: 'localhost'
  port: '5432'
  database: 'cgcrepair'


log.colorlog:

### Where the log file lives (no log file by default)
  file: '/tmp/cgc-repair.log'

### Whether or not to log the database queries
  database: false

### The level for which to log.  One of: info, warning, error, fatal, debug
  level: info

### Whether or not to log to console
  to_console: true

### Whether or not to rotate the log file when it reaches `max_bytes`
  rotate: true

### Max size in bytes that a log file can grow until it is rotated.
  max_bytes: 512000

### The maximun number of log files to maintain when rotating
  max_files: 4
